package Firstock

const base_url = "https://connect-go.thefirstock.tech/V1"
const config_file_path = "../firstock/config.json"
const j_key = "jkey"
const status_val = "status"
const success_status = "success"
const susertoken = "susertoken"
const data = "data"

// URLs
const login_url = base_url + "/login"
const logout_url = base_url + "/logout"
const user_details_url = base_url + "/userDetails"
const place_order_url = base_url + "/placeOrder"
const order_margin_url = base_url + "/orderMargin"
const single_order_history_url = base_url + "/singleOrderHistory"
const cancel_order_url = base_url + "/cancelOrder"
const modify_order_url = base_url + "/modifyOrder"
const trade_book_url = base_url + "/tradeBook"
const rms_limit_url = base_url + "/limit"
const position_book_url = base_url + "/positionBook"
const holdings_url = base_url + "/holdings"
const order_book_url = base_url + "/orderBook"
const get_expiry_url = base_url + "/getExpiry"
const brokerage_calculator_url = base_url + "/brokerageCalculator"
const basket_margin_url = base_url + "/basketMargin"
const get_security_info = base_url + "/securityInfo"
const product_conversion_url = base_url + "/productConversion"
const get_quote_url = base_url + "/getQuote"
const get_quote_ltp_url = base_url + "/getQuote/ltp"
const get_multi_quotes_url = base_url + "/getMultiQuotes"
const get_multi_quotes_ltp_url = base_url + "/getMultiQuotes/ltp"
const index_list_url = base_url + "/indexList"
const search_scrips_url = base_url + "/searchScrips"
const option_chain_url = base_url + "/optionChain"
const time_price_series_url = base_url + "/timePriceSeries"

// Error messages
const login_failed = "login failed"
const login_first_to_logout = "login first to logout"
const login_first_to_fetch_user_details = "login first to fetch user details"
const failed_to_logout = "failed to logout"
const failed_to_fetch_user_details = "failed to fetch user details"
const error_placing_order = "error placing order"
const error_fetching_order_margin = "error fetching order margin"
const error_fetching_single_order_history = "error fetching single order history"
const error_cancelling_order = "error cancelling order"
const error_modifying_order = "error mofiying order"

const error_fetching_trade_book_details = "error fetching trade book details"
const error_fetching_rms_limit = "error fetching rms limit"
const error_fetching_position_book = "error fetching position book"
const error_fetching_holdings = "error fetching holdings"
const error_fetching_order_book = "error fetching order book"
const error_fetching_expiry_details = "error fetching expiry details"
const error_fetching_brokerage_calculator_details = "error fetching brokerage calculator details"
const error_fetching_basket_margin_details = "error fetching basket margin details"
const error_getting_security_info = "error getting security info"
const error_fetching_product_conversion_details = "error fetching product conversion details"

// -----------------------------------Connect-----------------------------
const error_get_quote = "error getting quote"
const error_get_quote_ltp = "error getting quote ltp"
const error_get_multi_quotes = "error getting multi quotes"
const error_get_multi_quotes_ltp = "error getting multi quotes ltp"
const error_fetching_index_list = "error fetching index list"
const error_fetching_search_scrips = "error fetching search scrips"
const error_fetching_option_chain = "error fetching option chain"
const error_fetching_time_price_series_regular_interval = "error fetching time price series regular interval"
const error_fetching_time_price_series_day_interval = "error fetching time price series day interval"
